# 데이터
소스: https://github.com/ECSIM/pem-dataset1/tree/master/Standard%20Test%20of%20Nafion%20Membrane%20112
### 구조
- Anode:
	- Carbon paper Ballard
	- Platinum-Carbon 20%
	- Nafion solution (27% weight)
	- 80ml Isopropyl alcohol
	- 20ml double distilled water
	- Loading of Platinum= 0.39 mg/cm2
- Cathode:
	- Carbon paper Ballard
	- Platinum-Carbon 20%
	- Nafion solution (25% weight)
	- 80ml Isopropyl alcohol
	- 20ml double distilled water
	- Loading of Platinum= 0.39 mg/cm2

### 실험 환경
- Cell temperature= 75 C
- Anode temperature= 80 C
- Cathode temperature= 48-59-70-75 C

# 데이터 다운로드

In [ ]:
import urllib.request
urllib.request.urlretrieve("https://raw.githubusercontent.com/GuGroup/ShortNNTutorial/main/NNExample/data.csv", "data.csv")

('data.csv', <http.client.HTTPMessage at 0x7f5a964b5300>)

# 데이터 분석
데이터 분석
<img src="https://github.com/GuGroup/ShortNNTutorial/blob/main/NNExample/img/data.png?raw=1" style="max-width: 800px;">

A열 - 전류 밀도 - 예측 하고 싶은 값

B열 - 셀 전압   - input 1

C열 - 수소 압력 - input 2

D열 - 상대 습도 - input 3

E열 - 막 압축   - input 4

<img src="https://github.com/GuGroup/ShortNNTutorial/blob/main/NNExample/img/plots.png?raw=1" style="max-width: 800px;">

# 파이썬상에서 데이터 불러오기

In [ ]:
import numpy as np
data = np.genfromtxt('data.csv',delimiter=',')
print(data)
data = data[1:,:]
print(data.shape)
print(data)

[[     nan      nan      nan      nan      nan]
 [1.45e+03 2.51e-01 5.00e+00 3.00e+01 5.00e+00]
 [1.36e+03 3.01e-01 5.00e+00 3.00e+01 5.00e+00]
 ...
 [1.34e+03 2.84e-01 2.50e+01 1.00e+02 1.80e+01]
 [1.42e+03 2.34e-01 2.50e+01 1.00e+02 1.80e+01]
 [1.51e+03 1.83e-01 2.50e+01 1.00e+02 1.80e+01]]
(562, 5)
[[1.45e+03 2.51e-01 5.00e+00 3.00e+01 5.00e+00]
 [1.36e+03 3.01e-01 5.00e+00 3.00e+01 5.00e+00]
 [1.26e+03 3.51e-01 5.00e+00 3.00e+01 5.00e+00]
 ...
 [1.34e+03 2.84e-01 2.50e+01 1.00e+02 1.80e+01]
 [1.42e+03 2.34e-01 2.50e+01 1.00e+02 1.80e+01]
 [1.51e+03 1.83e-01 2.50e+01 1.00e+02 1.80e+01]]


In [ ]:
y = data[:,0]
x = data[:,1:]
print(y.shape,x.shape)

# 데이터 Feature Scaling

In [ ]:
x_mean = x.mean(0)
x_std = x.std(0)
x_scaled = (x-x_mean)/x_std

y_mean = y.mean(0)
y_std = y.std(0)
y_scaled = (y-y_mean)/y_std


# 모델 구축

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier

model = MLPRegressor((64,64),max_iter=1000,alpha=0.001)

# 모델 학습

In [ ]:
model.fit(x_scaled,y_scaled)

# 예측 그림 그리기

In [ ]:
print(x_scaled[:15,:])

In [ ]:
# (x_scaled*x_std + x_mean)
x[:15,:]

모델 예측

In [ ]:
y_predicted = model.predict(x_scaled)
y_predicted_unscaled = y_predicted*y_std + y_mean

In [ ]:
import matplotlib.pyplot as plt
plt.figure()
plt.scatter(x[:14,0],y_predicted_unscaled[:14])
plt.scatter(x[:14,0],y[:14])
plt.ylabel('current density [mA/cm2]')
plt.xlabel('voltage [V]')
plt.ylim([0,2200])
plt.xlim([0,1.1])
